import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";

const LoginActivityReport = dynamic(
  import("reportLoginActivity/reportLoginActivity"),
  { ssr: false }
);
const TerminatedParticipantReport = dynamic(
  import("reportTerminatedParticipant/reportTerminatedParticipant"),
  { ssr: false }
);

export default function Home() {
  return (
    <>
      <Head>
        <title>PerformX Micro-frontEnd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
      <div className={styles.parent}>
        <div className={styles.child}>Header</div>
        <div className={styles.main}>
          <div className={styles.child}>Sidebar</div>
          <div className="child content">
            <LoginActivityReport />
            <TerminatedParticipantReport />
          </div>
        </div>
        <div className={styles.child}>Footer</div>
      </div>
    </>
  );
}
